export const services = [
  {
    id: 1,
    name: 'Yard Work',
    freelancer: 'John Doe',
    price: '$20/hour',
    rating: 4.5,
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: 2,
    name: 'Indoor Painting',
    freelancer: 'Jane Smith',
    price: '$30/hour',
    rating: 4,
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: 3,
    name: 'Furniture Assembly',
    freelancer: 'Michael Lee',
    price: '$25/hour',
    rating: 3.2,
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: 4,
    name: 'Plumbing',
    freelancer: 'Alice Brown',
    price: '$40/hour',
    rating: 4.8,
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: 5,
    name: 'Yard Work',
    freelancer: 'David White',
    price: '$35/hour',
    rating: 4.3,
    image: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: 6,
    name: 'House Cleaning',
    freelancer: 'Maria Garcia',
    price: '$20/hour',
    rating: 4.7,
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: 7,
    name: 'Gardening',
    freelancer: 'Robert Martinez',
    price: '$25/hour',
    rating: 4.1,
    image: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: 8,
    name: 'Dog Walking',
    freelancer: 'Olivia Johnson',
    price: '$15/hour',
    rating: 4.9,
    image: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    id: 9,
    name: 'Furniture Assembly',
    freelancer: 'William Rodriguez',
    price: '$10/hour',
    rating: 3.9,
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: 10,
    name: 'Photography',
    freelancer: 'Sophia Wilson',
    price: '$50/hour',
    rating: 4.6,
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
  {
    id: 11,
    name: 'Plumbing',
    freelancer: 'Daniel Moore',
    price: '$55/hour',
    rating: 4.4,
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    id: 12,
    name: 'House Cleaning',
    freelancer: 'Isabella',
    price: '$40/hour',
    rating: 4.2,
    image: 'https://randomuser.me/api/portraits/women/12.jpg',
  },
  {
    id: 13,
    name: 'House Cleaning',
    freelancer: 'Ethan',
    price: '$30/hour',
    rating: 4.8,
    image: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    id: 14,
    name: 'Electrical',
    freelancer: 'Mia',
    price: '$60/hour',
    rating: 4.5,
    image: 'https://randomuser.me/api/portraits/women/14.jpg',
  },
  {
    id: 15,
    name: 'Electrical',
    freelancer: 'Aiden',
    price: '$20/hour',
    rating: 4.7,
    image: 'https://randomuser.me/api/portraits/men/15.jpg',
  },
  {
    id: 16,
    name: 'Yard Work',
    freelancer: 'Sofia',
    price: '$25/hour',
    rating: 4.3,
    image: 'https://randomuser.me/api/portraits/women/16.jpg',
  },
  {
    id: 17,
    name: 'Gardening',
    freelancer: 'Elijah',
    price: '$35/hour',
    rating: 4.1,
    image: 'https://randomuser.me/api/portraits/men/17.jpg',
  },
  {
    id: 18,
    name: 'Dog Walking',
    freelancer: 'Avery',
    price: '$15/hour',
    rating: 4.9,
    image: 'https://randomuser.me/api/portraits/women/18.jpg',
  },
  {
    id: 19,
    name: 'Photography',
    freelancer: 'James',
    price: '$50/hour',
    rating: 4.6,
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    id: 20,
    name: 'Plumbing',
    freelancer: 'Aria',
    price: '$55/hour',
    rating: 4.4,
    image: 'https://randomuser.me/api/portraits/women/20.jpg',
  },
]
